server:
  port: 8081


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
          ddl-auto: update
          show-sql: true
          properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-95976939.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa9l5baewiXKgnXb5d7
            client-secret: _rAcapHSj8BM48Yzp4vkJZ20M59Anehn_nL43o05

        provider:
          okta:
            issuer-uri: https://dev-95976939.okta.com/oauth2/default


#  profiles:
#    active: dev



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enable: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

okta:
  oauth2:
    issuer: https://dev-95976939.okta.com/oauth2/default
    audience: api://default





